version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: simdb
      POSTGRES_USER: simuser
      POSTGRES_PASSWORD: simpass
    ports:
      - "55432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/simdb
      SPRING_DATASOURCE_USERNAME: simuser
      SPRING_DATASOURCE_PASSWORD: simpass
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  pgdata: 