name: CD - Docker Build and Push

on:
  push:
    branches: [main, master]

env:
  REGISTRY: ghcr.io
  IMAGE_BACKEND: discrete-event-simulator-backend
  IMAGE_FRONTEND: discrete-event-simulator-frontend
  ACTOR: ${{ github.actor && toLower(github.actor) }}
  # To switch to AWS ECR, set REGISTRY and image names accordingly

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      # Login to GitHub Container Registry (or ECR if you switch)
      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.ACTOR }}
          password: ${{ secrets.GITHUB_TOKEN }}
          # For AWS ECR, use: aws-actions/amazon-ecr-login@v2

      # Build and push backend image
      - name: Build backend image
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.ACTOR }}/${{ env.IMAGE_BACKEND }}:latest .
      - name: Push backend image
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.ACTOR }}/${{ env.IMAGE_BACKEND }}:latest

      # Build and push frontend image
      - name: Build frontend image
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.ACTOR }}/${{ env.IMAGE_FRONTEND }}:latest ./frontend
      - name: Push frontend image
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.ACTOR }}/${{ env.IMAGE_FRONTEND }}:latest

# To switch to AWS ECR:
# - Set REGISTRY to ECR registry URL
# - Use aws-actions/configure-aws-credentials and aws-actions/amazon-ecr-login
# - Update IMAGE_BACKEND and IMAGE_FRONTEND as needed 